# Generated by Django 3.2.5 on 2022-05-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='smart',
        ),
    ]
