# Generated by Django 3.2.5 on 2022-06-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220607_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prenom',
            new_name='last_name',
        ),
    ]
