# Generated by Django 3.2.5 on 2022-06-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220608_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first',
            new_name='first_name',
        ),
    ]
